module.exports = {
  caseType:'association_official_record', initialState:'draft',
  states:['draft','noticed','owner_response','board_review','approved','appealed','resolved','recorded'],
  createRoles:['manager','board_secretary'],
  evidenceKinds:['ownership_snapshot','governing_document_version','notice_receipt','ledger_snapshot','meeting_minutes','ballot_tally','vendor_record','appeal_submission'],
  requiredSignals:['ownershipVersion','governingDocumentVersion','noticeDeadline','evaluatedAt','quorumRequired','quorumPresent','policyVersion'],
  assessmentRoles:['manager','board_secretary','board_member','appeals_panel'],
  auditRoles:['manager','board_secretary','appeals_panel'],
  connectorRoles:['manager','board_secretary'],
  professionalBoundary:'This workflow preserves association procedure and records; it does not determine legal rights or replace association counsel.',
  connectors:[
    {name:'accounting',purpose:'ledger reconciliation'},
    {name:'payments',purpose:'payment receipts without storing credentials'},
    {name:'property_records',purpose:'ownership snapshots'},
    {name:'esignature',purpose:'signed notice and approval receipts'},
    {name:'calendar',purpose:'meeting and deadline synchronization'},
    {name:'voting',purpose:'ballot and quorum evidence'},
    {name:'maintenance',purpose:'work-order status'},
    {name:'messaging',purpose:'notice delivery receipts'},
  ],
  transitions:[
    {from:'draft',action:'issue_notice',to:'noticed',roles:['manager'],requiresEvidence:true},
    {from:'noticed',action:'record_response',to:'owner_response',roles:['owner','manager'],requiresEvidence:true},
    {from:'owner_response',action:'submit_board_review',to:'board_review',roles:['manager'],requiresEvidence:true},
    {from:'board_review',action:'approve',to:'approved',roles:['board_member'],requiresEvidence:true,dualControl:true},
    {from:'approved',action:'appeal',to:'appealed',roles:['owner'],requiresEvidence:true},
    {from:'appealed',action:'resolve',to:'resolved',roles:['appeals_panel'],requiresEvidence:true,dualControl:true},
    {from:'approved',action:'record',to:'recorded',roles:['board_secretary'],requiresEvidence:true,dualControl:true},
    {from:'resolved',action:'record',to:'recorded',roles:['board_secretary'],requiresEvidence:true,dualControl:true},
  ],
  assess:x=>({disposition:new Date(x.noticeDeadline)>new Date(x.evaluatedAt)&&Number(x.quorumPresent)>=Number(x.quorumRequired)?'eligible_for_board_review':'procedural_hold',enforcementDecision:null,versions:{ownership:x.ownershipVersion,governingDocument:x.governingDocumentVersion}}),
};
